### ISSUE TITLE
[BUG] Elements not using the global settings don't treat having a target as being in combat

### ISSUE THREAD

**Issue by AEllinger** [PhenomDevel/BlizzHUDTweaks#10]
Anything that does not use the global settings no longer treats having a target as being in combat. The elements using global settings still behave as expected. I believe this changed as of the last version, but I can't swear to that.

**Comment by PhenomDevel** [comment]
I added the ability to change `Treat target as in combat` for each actionbar/frame by itself. Maybe i forgot to turn it on by default so it behaves the same as in the last release.

Can you confirm that `Treat target as in combat` is not checked on the frames which have `Use global options` disabled?
