### ISSUE TITLE
[FEATURE] fading condition for health or/and power (primary) below X% and fading condition for when the quest tracker is updated.

### ISSUE THREAD

**Issue by antarek** [PhenomDevel/BlizzHUDTweaks#14]
## Idea
Currently BHT doesn't allow you to have the player unitframe displayed when either your health or power is below a certain %.
Currently BHT doesn't allow you to have the quest tracker displayed when it gets updated.

## Solution
Add a new condition to allow UI elements to be displayed when health or/and power (primary) is/are below a certain %.
Add a new condition to allow the quest tracker to be displayed when it gets updated.

**Comment by PhenomDevel** [comment]
Hey idea of fading for a certain health % i get. The one for your energy i don't see any usecase for it. Could you please elaborate what you would want to use it for?

The objective tracker "Flash" when it updates should be doable and will be added to misc options.

**Comment by PhenomDevel** [comment]
Objective tracker flash is added in `1.25.0-beta`

**Comment by HyenaHorror** [comment]
> The one for your energy i don't see any usecase for it. Could you please elaborate what you would want to use it for?

It would be useful when the character is below X% mana. Even though you're not _in combat_ you're still _vulnurable_, just as you would be when low health. I'm not sure about other class resources.

**Comment by antarek** [comment]
Indeed. For exemple if i play a healer i want to be able to monitor my mana without being forced to target myself when my mana is recharging. So having an option to show an UI element while that your power is below a certain % would do the trick.

**Comment by PhenomDevel** [comment]
I added on option in the upcoming release to fade by health percent. But for the power fade in my opionion it is to much of a niche to be implemented and be helpful for a lot of ppl. I guess this would be disabled by 95%+ of users.

**Comment by PhenomDevel** [comment]
Health fade is Implemented in `1.27.0-beta`.
