### ISSUE TITLE
[BUG] Mouseover Frame Fading, Toggle Keybind reacts to wrong keys

### ISSUE THREAD

**Issue by beijer** [PhenomDevel/BlizzHUDTweaks#19]
## Description
> Please describe what the problem is as precise as possible

Toggle keybind reacts all letters in the name of the bound key.
For example, NUMPADMULTIPLY reacts to pressing all keys in the name of the key (A,D,N etc.)

## Reproduce
> What steps are needed to reproduce it?

1. Bind Toggle Keybind to NUMPADMULTIPLY
2. Start moving with A, D

## Expected Behaviour
> What did you expect what should have happend?

Not react to other keys.

**Comment by PhenomDevel** [comment]
Should be fixed in `1.25.1-beta`
