### ISSUE TITLE
[FEATURE] Hide ActionBar 1 Buttons

### ISSUE THREAD

**Issue by hovrawl** [PhenomDevel/BlizzHUDTweaks#20]
Unsure if it is possible with lua but are we able to hide the buttons from Action Bar 1 that are not filled like the rest of the bars?
Would be awesome for a tweak to override the default option of not hiding it, also potentially hiding the first bar altogether would be a nice option.

**Comment by PhenomDevel** [comment]
Version `1.25.2-beta` lets you hide the unused action bar 1 buttons. Hiding the action bar can therefore archived by not placing anything on it.

**Comment by PhenomDevel** [comment]
Ok it is more like `1.25.5-beta` 👍

**Comment by hovrawl** [comment]
You're a massive legend! Thanks for adding the tweak in mate, I am not super great with Lua let alone the Blizz api and thought it would take me far too long to do this!
