### ISSUE TITLE
[USABILITY] GitHub Builds & Addon Managers

### ISSUE THREAD

**Issue by twistedmywords** [PhenomDevel/BlizzHUDTweaks#21]
## Problem
You are currently unable to use addon managers (like CurseBreaker) to download and install this addon via GitHub.

## Desired solution
Packaging releases in a compatible way with addon managers that allow downloading from GitHub.

Is this something you would be willing to do for future releases?

**Comment by PhenomDevel** [comment]
With the upcoming version (`1.25.5-beta` and beyond) the complete package with libs will also be available on github.
