### ISSUE TITLE
[FEATURE] Hiding Borders

### ISSUE THREAD

**Issue by OttoDeFe** [PhenomDevel/BlizzHUDTweaks#24]
## Idea
Would it be possible to add border hiding on unit frames and action bars? I've tried Borderless and it doesn't seems to work with EditModeExpanded.

## Solution
> Try to describe the solution you are aiming for

**Comment by OttoDeFe** [comment]
Just did a little bit of checking - what I'm looking for is removal of the button borders and the droplet shaped border on the unit frame portraits.

**Comment by PhenomDevel** [comment]
I have no plans on adding this currently. Personally i use HideActionBarBorders for the actionbars. This won't fix the problem with the character frame though.

**Comment by OttoDeFe** [comment]
Fair enough. Thanks for recommend; I'll give it a go!
