### ISSUE TITLE
Addon not loading - Cannot find a library instance of "AceAddon-3.0"

### ISSUE THREAD

**Issue by mabramo** [PhenomDevel/BlizzHUDTweaks#27]
## Problem
Addon not loading - Cannot find a library instance of "AceAddon-3.0"

Here is the full text of the first error message. I have grabbed the zip from the latest release version and manually placed the BlizzHUDTweaks folder in my addons folder. I'm using a computer with a linux based distro, if that matters (it shouldn't). 

Message: Interface/AddOns/BlizzHUDTweaks/BlizzHUDTweaks.lua:2: attempt to call global 'LibStub' (a nil value)
Time: Mon Nov 28 01:00:57 2022
Count: 1
Stack: Interface/AddOns/BlizzHUDTweaks/BlizzHUDTweaks.lua:2: attempt to call global 'LibStub' (a nil value)
[string "@Interface/AddOns/BlizzHUDTweaks/BlizzHUDTweaks.lua"]:2: in main chunk

Locals: _ = "BlizzHUDTweaks"
BlizzHUDTweaks = <table> {
}
(*temporary) = nil
(*temporary) = "AceAddon-3.0"
(*temporary) = "attempt to call global 'LibStub' (a nil value)"

**Comment by PhenomDevel** [comment]
Hey there,

in the latest *Release* `1.24.2` the project wasn't build in a compatible way for GitHub. Therefore placing it in the Addons folder will not work. This will only work with the current Beta releases and further.

If you still got any problem with the beta releases let me know. 

Cheers.
