### ISSUE TITLE
[BUG] Out of Combat fade delay option issues

### ISSUE THREAD

**Issue by ryannotfound** [PhenomDevel/BlizzHUDTweaks#29]
Using Combat fade together with an Out of Combat Fade Delay (example, setting to 5 seconds) produces bad behaviors. Exiting combat but then re-engaging combat within that fade delay (5 seconds in this example) will cause the out of combat fade to occur even when in combat. This is not noticeable with the default Fade Delay value of 0 since there is no overlap. The out of combat fade should be completely ignored/cancelled or otherwise deprioritized when re-entering combat.

Easily reproduceable - just set the out of combat fade delay to 5-10 seconds and then start combat within this period.

**Comment by ryannotfound** [comment]
wanted to mention this also works with simple targeting when the "Treat target as in combat" option is selected. Using the delay example above (5 seconds), simple way to reproduce is to click a target, wait until the fade-in is completely done (maybe wait a full second), unselect the target, then reselect the same target.  After a few seconds the out of combat fade will take place even when the target is still selected.

**Comment by PhenomDevel** [comment]
I can reproduce the problem. I'll be checking this in a few days since i'm, busy with DF :P

**Comment by PhenomDevel** [comment]
Implemented in `1.27.0-beta`.
