### ISSUE TITLE
[FEATURE] Hide pet status text (health/percentage)

### ISSUE THREAD

**Issue by ryannotfound** [PhenomDevel/BlizzHUDTweaks#31]
## Idea
Small feature request to hide pet health/percentage when Status Text is set to show in interface options. The bar is so small that when using "both" it makes it difficult to see the actual bar at a glance, and this is how Target of Target is handled by default.

**Comment by PhenomDevel** [comment]
This will be implemented in the upcoming release.

**Comment by PhenomDevel** [comment]
Implemented in `1.27.0-beta`. (Does not always work, will have to work on it further)

**Comment by PhenomDevel** [comment]
This is now implemented in a way where you can enable/disable it.
