### ISSUE TITLE
[BUG] Minimap not fading with Immersion addon

### ISSUE THREAD

**Issue by zorker** [PhenomDevel/BlizzHUDTweaks#33]
## Description
> When the Immersion addon is installed the minimap fading does not work. 

## Reproduce
> What steps are needed to reproduce it?
Install Immersion and the minimap fading breaks.

That is not a big deal for me, just sth. I noticed.

**Comment by PhenomDevel** [comment]
The minimap fading is broken anways since it does not always show the actual texture. And because it is related to another addon i won't fix this for now. Therefore closing the ticket.
