### ISSUE TITLE
[BUG] ExtraActionBarFrame always fading

### ISSUE THREAD

**Issue by zorker** [PhenomDevel/BlizzHUDTweaks#34]
## Description
> I want the Extra Action Button to always be visible. My global setting is out of combat fading to zero. So most of the stuff stays hidden.
I am in the Garrison to check the ExtraButton. I cannot get it to the point where it does not fadeout. 

*update* I might take that back. Maybe the Draenor button frame is a seperate type of action bar. You can drag the ability out of it and the bar disapears for example.

## Reproduce
Go to Garrison. Try to disable frame fading for the ExtraActionButton. It always fades.

## Expected Behaviour
ExtraActionButton should respect button specific settings.

**Comment by PhenomDevel** [comment]
Are you sure it is the ExtraActionButton? The Garrison ability is anotehr frame called `ZoneAbilityFrame`. Maybe you have to disable it for this aswell.

**Comment by zorker** [comment]
Yeah I am not really sure. I need more of those ExtraActionButtons to test it.

**Comment by PhenomDevel** [comment]
I'll close this since i believe the problem was the above comment. If you have new information we can reopen it :)
