### ISSUE TITLE
[BUG] Actionbar fades out on SpellFlyout

### ISSUE THREAD

**Issue by zorker** [PhenomDevel/BlizzHUDTweaks#35]
## Description
> When you have a button that triggers the spellflyout frame like portals (mage) or any pandaria portals when you have that button on the action bar and leave the bar to select any portal the bar gets hidden.

That is a problem if like in my case the alpha value is zero for on mouse out.

Here is like I fixed that in rLib for my framefader for rActionBars. I would like to not do that myself again.

https://github.com/zorker/rothui/blob/master/wow8.0/rLib/framefader.lua#L102

When the Spellflyout becomes visible you can save the bar you are over and you can check for is the mouse still over the spellflyout before triggering the fadeout.

https://github.com/zorker/rothui/blob/master/wow8.0/rLib/framefader.lua#L102

## Reproduce
> Get any spell on the bar that triggers Spellflyout (Mage portals or Pandaria portals). Try to hover a portal and the fader will activate.

## Expected Behaviour
> Make it so the fadeout only happens when the mouse leaves the spellflyout.

**Comment by PhenomDevel** [comment]
Thanks for the example. Will have a look. But may take some time since i am busy with DF. But this is actually something that bothers me aswell...

**Comment by PhenomDevel** [comment]
Implemented in `1.27.3-beta`

**Comment by zorker** [comment]
Works perfectly. Thank you.
