### ISSUE TITLE
[FEATURE] Disable fadiing of actionbar1 when dragonriding

### ISSUE THREAD

**Issue by Rezy942** [PhenomDevel/BlizzHUDTweaks#39]
## Idea
> Currently, there is no way to disable fading of action bar used for dragonriding skills. (NOT the encounter bar!)

## Solution
> Add a specific toggle to disable fading of this bar in global settings, similar to MouseoverActionBars addon. (which is a worse version of this addon)
Also, this option would respect users choice of bar-art ON or OFF. (if possible)

## Optional Context (e.g. Screenshots, Scribbles ...)
![image](https://user-images.githubusercontent.com/122007087/211169982-b6ed8e07-b19c-4219-9f2f-5da68765796f.png)

**Comment by PhenomDevel** [comment]
That is not as easy as a lot of other load options. Though WeakAuras hjas already solved it. I'll take a look and see if i can use some of the code: https://github.com/WeakAuras/WeakAuras2/commit/0ff498704a3c07159c81e1b3841c4c172887d5d2

**Comment by Rezy942** [comment]
Perhaps MouseoverActionBars addon has some code you can use. Their implementation is pretty good too.

**Comment by PhenomDevel** [comment]
1.31.0-beta has options to fade for vehicles. Try it out and let me know if this fits your needs.

**Comment by PhenomDevel** [comment]
I close this issue since there was no more response after version 1.31.0-beta.

**Comment by Rezy942** [comment]
Sorry i missed this reply
Not sure how to download beta but if dragonriding is a vehicle then im sure it will work great
Thank you
