### ISSUE TITLE
[BUG] Unable to reset certain settings to default without resetting entire profile

### ISSUE THREAD

**Issue by ghost** [PhenomDevel/BlizzHUDTweaks#42]
## Description / Reproduce
When setting "player health font size" or "player mana font size", default is set to "0" which is not true.
After user changes this setting, going back to default is hard as it doesnt show anywhere what the actual default is, and there is no button to do so.
This applies to all other similar sliders like in target.

Resetting profile works, but sadly user can make WAY too many changes in other menus that resetting profile would suck!

## Expected Behaviour
Option 1:
add an easily visible tag somewhere maybe below sliders indicating what the default blizzard value is.
option 2:
add a button to reset each slider back to default.
Also, by default, slider should show current font size, not just 0.

## Optional Context (e.g. Screenshots)
![image](https://user-images.githubusercontent.com/122007087/212482254-a6e58e64-49bb-4113-bfaa-bf92163b980e.png)

**Comment by Rezy942** [comment]
Update: same exact issue with misc -> action bars sliders.
All are set to 0 by default. 0 is not the default for blizzard bars.
Ideally the 0 should indicate the default.

**Comment by PhenomDevel** [comment]
Should be easy to add a reset button for each page. 

I won't have "0" to be the default because it is not correct. The blizz default ist depending on the user setting within the edit mode. Since i can't easily control this you can "reset" it by just disabling the actionbar padding for the choosen bar.

**Comment by Rezy942** [comment]
I see, thank you for clarifying.
I think best solution is as you said to add the reset to default button.
I suppose disabling padding works as well, although it feels less "natural" way to go back to default, and once user re-enables it, the value wont go back to default. 
Not a big deal at all. A reset button would make it slightly more user friendly :)
