### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by kirin6666** [PhenomDevel/BlizzHUDTweaks#44]
## Description
> Please describe what the problem is as precise as possible
Since 10.0.5 hit my bag and microbars are no longer being faded.

## Reproduce
> What steps are needed to reproduce it?
1.https://imgur.com/a/GRG54Vk
2.https://imgur.com/a/QrEiW3d
3. ?!?!
4. Profit

## Expected Behaviour
Should be hidden as it was pre-10.0.5

## Optional Context (e.g. Screenshots)
Already put earlier. Probably connected with Blizzard giving u options to edit them on their own UI.

**Comment by jobackman** [comment]
+1 on this! Started after 10.0.5 when they updated the edit mode to include bags and micromenu as separate editable elements

**Comment by PhenomDevel** [comment]
Should be fixed in the newest version. Those frames have new settings though. So you might have to configure them again.

**Comment by jobackman** [comment]
Thanks ❤️
