### ISSUE TITLE
[FEATURE] Fade delay after mouseover

### ISSUE THREAD

**Issue by 01d9a6aa** [PhenomDevel/BlizzHUDTweaks#48]
Hi PhenomDevel!

## Idea
> It would be awesome if we could add a delay to the fade on leaving mouseover, so that frames retain mouseover alpha for a little while after leaving mouseover.

## Solution
> Perhaps analogous to the leave combat fade delay.

**Comment by 01d9a6aa** [comment]
Loving the addon by the way, big shout out to your work here!

**Comment by PhenomDevel** [comment]
Like #30 it's is not as easy at it seems. Therefore nothing i am willing to commit time into currently, sry.
