### ISSUE TITLE
[BUG] Cooldown Pulse visible on bars with 0 opacity.

### ISSUE THREAD

**Issue by Sythr4l** [PhenomDevel/BlizzHUDTweaks#51]
## Description
> I'm not sure if this issue belongs to Masque, Masque Blizzard Bars or your addon.   Utilizing Masque and the Masque Blizzard Bars addons with Cooldown Pulse enabled causes the cooldown pulse to show on bars that are 0% Alpha.  

## Reproduce
> What steps are needed to reproduce it?
1. Use Masque and the Masque Blizzard Bars addons with BlizzHudTweaks. with Cooldown Pulse enabled in Masque.
2. Set a bar to 0 Alpha.
3. Utilize a spell and the spell flash shows up on the bar that is 0 Alpha.

## Expected Behaviour
> What did you expect what should have happend?
Cooldown pulse only visible on visible bars.

## Optional Context (e.g. Screenshots)
This does not occur with a similar addon "MouseoverActionBars - Mouseover Action Bars".  Would prefer to utilize BlizzHudTweaks as it has expanded functionality I prefer :)

![image](https://github.com/PhenomDevel/BlizzHUDTweaks/assets/113131440/1ae6416b-1883-4873-9bd4-ddb39d004166)

**Comment by PhenomDevel** [comment]
There was already something to prevent this. I looked at the code of "MouseoverActionBars" and it is actually 100% the same code. I moved the execution of the code to a different location. I couldn't reproduce it even with Masque and the Masque Blizzard Bars addons installed.

Please let me know if this fixes it for you in 1.33.5.

Cheers

**Comment by Sythr4l** [comment]
That appears to have fixed it!  Appreciate you responding and providing a fix so quickly.  :)
