### ISSUE TITLE
[BUG] BugSack caught this bug not sure it it is useful to you

### ISSUE THREAD

**Issue by GJordao** [PhenomDevel/BlizzHUDTweaks#53]
## Description
> Please describe what the problem is as precise as possible

This happens often, I don't know exactly when but I think it relates to getting to combat. I will paste the log below

## Reproduce
> What steps are needed to reproduce it?
1. I was just leveling a toon, no dungeon no nothing just doing quests

## Expected Behaviour
> What did you expect what should have happend?
No bug go caught

## Optional Context (e.g. Screenshots)
18x [ADDON_ACTION_BLOCKED] AddOn 'BlizzHUDTweaks' tried to call the protected function 'PlayerFrameBottomManagedFramesContainer:Show()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `Show'
[string "@BlizzHUDTweaks/ClassResource.lua"]:113: in function `Restore'
[string "@BlizzHUDTweaks/EventHandler.lua"]:226: in function `?'
[string "@BattleGroundEnemies/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ies/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@BattleGroundEnemies/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ies/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@BattleGroundEnemies/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@BetterWardrobe/Libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...ns/BetterWardrobe/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:486
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:486
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:486
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:552
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:552
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:546
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:561
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:506
}

**Comment by GJordao** [comment]
145x [ADDON_ACTION_BLOCKED] AddOn 'BlizzHUDTweaks' tried to call the protected function 'PlayerFrameBottomManagedFramesContainer:SetPoint()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetPoint'
[string "@BlizzHUDTweaks/ClassResource.lua"]:58: in function `SetPoint'
[string "@BlizzHUDTweaks/ClassResource.lua"]:38: in function `RestorePosition'
[string "@BlizzHUDTweaks/ClassResource.lua"]:123: in function `Restore'
[string "@BlizzHUDTweaks/EventHandler.lua"]:226: in function `?'
[string "@BattleGroundEnemies/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ies/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@BattleGroundEnemies/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ies/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@BattleGroundEnemies/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@BetterWardrobe/Libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...ns/BetterWardrobe/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

**Comment by PhenomDevel** [comment]
This is caused due to protected functions i am calling. Those will be protected by the ui in some circumstances and there is not much i can do about it. I tried solving it but wasn't able to in the time invested.

I'll have a look when the next big patch/addon comes out. But until then i don't think i'll be able to fix it.
