### ISSUE TITLE
[BUG] Alpha reduction suddenly not working anymore for some UI elements

### ISSUE THREAD

**Issue by durrburger93** [PhenomDevel/BlizzHUDTweaks#56]
Reducing the alpha for certain UI elements is suddenly not working after the latest update, but I think the issue suddenly started a few days after the update rather than immediately after updating the addon.

With the minimap, for example, the header below the map still obeys alpha rules, but the minimap itself doesn't. 

## Reproduce
Set te alpha to less than 100%.

## Expected Behaviour
For the entire minimap to become more transparent rather than just the header.

Here are my minimap settings and how it looks like compared to the map header: https://imgur.com/a/cfREuSW 

Edit: disregard the missing map on the first SS since I disabled it via a keybind at the time by mistake.

**Comment by PhenomDevel** [comment]
No more answer since april. Closed.
