### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Sythr4l** [PhenomDevel/BlizzHUDTweaks#57]
## Description
This error appeared in game when starting a mythic plus dungeon.  It occurred right when the first enemy was encountered.

## Optional Context (e.g. Screenshots)
1x [ADDON_ACTION_BLOCKED] AddOn 'BlizzHUDTweaks' tried to call the protected function 'PlayerFrameBottomManagedFramesContainer:SetPoint()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `SetPoint'
[string "@BlizzHUDTweaks/ClassResource.lua"]:58: in function `SetPoint'
[string "@BlizzHUDTweaks/ClassResource.lua"]:38: in function `RestorePosition'
[string "@BlizzHUDTweaks/ClassResource.lua"]:123: in function `Restore'
[string "@BlizzHUDTweaks/EventHandler.lua"]:192: in function `?'
[string "@BigWigs/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...igs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@BigWigs/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...igs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@BigWigs/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@BlizzHUDTweaks/Libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...ns/BlizzHUDTweaks/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507

**Comment by PhenomDevel** [comment]
Has this happened more than once? It sometimes happens when other addons interfere with what BHT is doing. If it's reproducible, I'll take a look.

**Comment by Sythr4l** [comment]
Hello, sorry for delay in response.  This happened again at the start of a mythic plus again.

1x [ADDON_ACTION_BLOCKED] AddOn 'BlizzHUDTweaks' tried to call the protected function 'PlayerFrameBottomManagedFramesContainer:SetPoint()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `SetPoint'
[string "@BlizzHUDTweaks/ClassResource.lua"]:58: in function `SetPoint'
[string "@BlizzHUDTweaks/ClassResource.lua"]:38: in function `RestorePosition'
[string "@BlizzHUDTweaks/ClassResource.lua"]:123: in function `Restore'
[string "@BlizzHUDTweaks/EventHandler.lua"]:192: in function `?'
[string "@BigWigs/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...igs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@BigWigs/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...igs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@BigWigs/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@BlizzHUDTweaks/Libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...ns/BlizzHUDTweaks/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507

**Comment by PhenomDevel** [comment]
This is caused due to protected functions i am calling. Those will be protected by the ui in some circumstances and there is not much i can do about it. I tried solving it but wasn't able to in the time invested.

I'll have a look when the next big patch/addon comes out. But until then i don't think i'll be able to fix it.
