### ISSUE TITLE
LUA Error - AddOn 'BlizzHUDTweaks' tried to call the protected function [BUG] 

### ISSUE THREAD

**Issue by mattenos** [PhenomDevel/BlizzHUDTweaks#59]
## Description
It appears at the start of mythic plus dungeons.
using v1.40.0

## Reproduce
> What steps are needed to reproduce it?
Settings:
1 - only active settings are for mouseover fading. ActionBars 1-4, pet action bar, rep/xp bar and stance bar. They are all linked.

## Expected Behaviour
> What did you expect what should have happend?

## Optional Context (e.g. Screenshots)
2x [ADDON_ACTION_BLOCKED] AddOn 'BlizzHUDTweaks' tried to call the protected function 'PlayerFrameBottomManagedFramesContainer:SetScale()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `SetScale'
[string "@BlizzHUDTweaks/ClassResource.lua"]:40: in function `RestorePosition'
[string "@BlizzHUDTweaks/ClassResource.lua"]:123: in function `Restore'
[string "@BlizzHUDTweaks/EventHandler.lua"]:192: in function `?'
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@BlizzHUDTweaks/Libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...ns/BlizzHUDTweaks/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

**Comment by PhenomDevel** [comment]
Do you have anything activated for the ClassRessource? The bug seems to come from the positioning of the ressource bar. 

It might be that i try to position it even though the settings is not activated. Will have a look in the near future.

**Comment by PhenomDevel** [comment]
See alos #60 
This is caused due to protected functions i am calling. Those will be protected by the ui in some circumstances and there is not much i can do about it. I tried solving it but wasn't able to in the time invested.
