### ISSUE TITLE
Periodically throwing errors, seems minor but annoying.

### ISSUE THREAD

**Issue by Khirgil** [PhenomDevel/BlizzHUDTweaks#62]
Here's the swatter bug report:
Date: 2024-01-17 01:37:12
ID: 1
Error occured in: Global
Count: 12
Message: Interface/AddOns/BlizzHUDTweaks/Miscellaneous.lua line 265:
   attempt to index field 'Background' (a nil value)
Debug:
   [string "@Interface/AddOns/BlizzHUDTweaks/Miscellaneous.lua"]:265: UpdateActionbar1UnusedButtons()
   [string "@Interface/AddOns/BlizzHUDTweaks/EventHandler.lua"]:238: ?()
   [string "@Interface/AddOns/BlizzHUDTweaks/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109:
      ...aks/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109
   [string "=[C]"]: ?
   [string "@Interface/AddOns/BlizzHUDTweaks/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19:
      ...aks/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15
   [string "@Interface/AddOns/BlizzHUDTweaks/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: Fire()
   [string "@Interface/AddOns/BlizzHUDTweaks/Libs/AceEvent-3.0/AceEvent-3.0.lua"]:120:
      ...ns/BlizzHUDTweaks/Libs/AceEvent-3.0/AceEvent-3.0.lua:119
Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface/AddOns/BlizzHUDTweaks/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 RestoreActionbarPadding = <function> defined @Interface/AddOns/BlizzHUDTweaks/Miscellaneous.lua:167
 NewModule = <function> defined @Interface/AddOns/BlizzHUDTweaks/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 EnableModule = <function> defined @Interface/AddOns/BlizzHUDTweaks/Libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @Interface/AddOns/BlizzHUDTweaks/Libs/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @Interface/AddOns/BlizzHUDTweaks/Libs/AceAddon-3.0/AceAddon-3.0.lua:438
 defaultModuleLibraries = <table> {
 }
 UpdateFontSize = <function> defined @Interface/AddOns/BlizzHUDTweaks/Miscellaneous.lua:138
 RestoreOriginal = <function> defined @Interface/AddOns/BlizzHUDTweaks/Miscellaneous.lua:270
 SetDefaultModulePrototype = <function> defined @Interface/AddOns/BlizzHUDTweaks/Libs/AceAddon-3.0/AceAddon-3.0.lua:405
 RestoreAll = <function> defined @Interface/AddOns/BlizzHUDTweaks/Miscellaneous.lua:281
 name = "BlizzHUDTweaks_Miscellaneous"
 IsEnabled = <function> defined @Interface/AddOns/BlizzHUDTweaks/Miscellaneous.lua:341
 orderedModules = <table> {
 }
 DisableModule = <function> defined @Interface/AddOns/BlizzHUDTweaks/Libs/AceAddon-3.0/AceAddon-3.0.lua:346
 RestoreActionbarPaddings = <function> defined @Interface/AddOns/BlizzHUDTweaks/Miscellaneous.lua:182
 RestoreActionbarOriginal = <function> defined @Interface/AddOns/BlizzHUDTweaks/Miscellaneous.lua:207
 SetFrameText = <function> defined @Interface/AddOns/BlizzHUDTweaks/Miscellaneous.lua:145
 IsModule = <function> defined @Interface/AddOns/BlizzHUDTweaks/Libs/AceAddon-3.0/AceAddon-3.0.lua:213
 SetDefaultModuleState = <function> defined @Interface/AddOns/BlizzHUDTweaks/Libs/AceAddon-3.0/AceAddon-3.0.lua:383
 InstallHooks = <function> defined @Interface/AddOns/BlizzHUDTweaks/Miscellaneous.lua:303
 SetEnabledState = <function> defined @Interface/AddOns/BlizzHUDTweaks/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 baseName = "BlizzHUDTweaks"
 enabledState = true
 GetValue = <function> defined @Interface/AddOns/BlizzHUDTweaks/Options/Miscellaneous.lua:553
 RestoreActionbarSize = <function> defined @Interface/AddOns/BlizzHUDTweaks/Miscellaneous.lua:155
 GetOptionsTable = <function> defined @Interface/AddOns/BlizzHUDTweaks/Options/Miscellaneous.lua:561
 defaultModuleState = true
 options = <table> {
 }
 Disable = <function> defined @Interface/AddOns/BlizzHUDTweaks/Miscellaneous.lua:324
 IterateModules = <function> defined @Interface/AddOns/BlizzHUDTweaks/Libs/AceAddon-3.0/AceAddon-3.0.lua:433
 Enable = <function> defined @Interface/AddOns/BlizzHUDTweaks/Miscellaneous.lua:333
 UpdateActionbar1UnusedButtons = <function> defined @Interface/AddOns/BlizzHUDTweaks/Miscellaneous.lua:239
 FlashObjectiveTracker = <function> defined @Interface/AddOns/BlizzHUDTweaks/Miscellaneous.lua:218
 moduleName = "Miscellaneous"
 GetName = <function> defined @Interface/AddOns/BlizzHUDTweaks/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 SetValue = <function> defined @Interface/AddOns/BlizzHUDTweaks/Options/Miscellaneous.lua:557
}
forcedAlpha = nil
buttons = 12
(*temporary) = nil
(*temporary) = nil
(*temporary) = 1
(*temporary) = 12
(*temporary) = "ActionButton12"
(*temporary) = ActionButton12 {
 CalculateAction = <function> defined @Interface/FrameXML/SecureTemplates.lua:609
 OnLeave = <function> defined @Interface/FrameXML/ActionButton.lua:1474
 FlyoutArrowContainer = Frame {
 }
 PlaySpellInterruptedAnim = <function> defined @Interface/FrameXML/ActionButton.lua:1233
 showButtonArt = true
 DoModeChange = <function> defined @Interface/FrameXML/QuickKeybind.lua:95
 UpdateButtonArt = <function> defined @Interface/FrameXML/ActionButton.lua:1511
 QuickKeybindButtonOnLeave = <function> defined @Interface/FrameXML/QuickKeybind.lua:33
 OnDragStart = <function> defined @Interface/FrameXML/ActionButton.lua:1442
 OnReceiveDrag = <function> defined @Interface/FrameXML/ActionButton.lua:1454
 icon = ActionButton12Icon {

AddOns:
  Swatter, v9.1.BETA.5.13 (OneMawTime)
  BlizzHUDTweaks, v1.41.0
  BlizRuntimeLib v10.2.5.52902(US) <enUS>
  (ck=6b)

**Comment by PhenomDevel** [comment]
Should be fixed in 1.42.0
