### ISSUE TITLE
[BUG] PlayerFrameBottomManagedFrames Error

### ISSUE THREAD

**Issue by modaddict** [PhenomDevel/BlizzHUDTweaks#66]
## Description
> It is seemingly at random that whenever I mouseover unitframes or enemies I get this error, usually in keys but sometimes in overworld. Today got a new/longer one doing a world boss. I'm not sure what addon could conflict outside of maybe FrameSort, Plater or Masque maybe? Nothing else I have should affect the UI/unitframes in this manner? Could Clique also be a conflict?

## Reproduce
> What steps are needed to reproduce it?
1. Mouseover unitframes/enemy unitframes or press spell while targeting them
2. Sometimes that will trigger the lua errors
3. That's it?

## Expected Behaviour
> Usually it does nothing and I can quest/do keys etc just fine. But occasionally it will throw up an error.

## Optional Context (e.g. Screenshots)
> Screenshots are kinda hard to take bc it often happens while im trying to kill something or heal in m+ lol. But I attached the text documents of the errors in notepad:
[blizzhudtweaks error 2.txt](https://github.com/PhenomDevel/BlizzHUDTweaks/files/14336280/blizzhudtweaks.error.2.txt)
[blizzhud tweaks error.txt](https://github.com/PhenomDevel/BlizzHUDTweaks/files/14336281/blizzhud.tweaks.error.txt)

**Comment by modaddict** [comment]
another error today:
[blizzhudtweaks error 3.txt](https://github.com/PhenomDevel/BlizzHUDTweaks/files/14389035/blizzhudtweaks.error.3.txt)

**Comment by modaddict** [comment]
Another today while questing, to do with Kaliel's tracker (i've had quite a few errors with this addon before, so not surprised. will have to tweak some settings & see if it's smth i can remedy myself, think it's the quest button? Though we didn't have to use one in this quest, it was just killing mobs lol).
[bht error 5.txt](https://github.com/PhenomDevel/BlizzHUDTweaks/files/14396349/bht.error.5.txt)

**Comment by PhenomDevel** [comment]
Hey, better late than never.

i can't reproduce it since i am not actively playing atm. 

The errors yoou are seeing are most likely in situation where the blizz UI is blocking some actions. This is sometimes the case depending on the state of there charatcer and nothing i can really do much about since there is not to much ican do with the standard ui. 

So i'd suggest iognoring it the best you can. Maybe iun the future the UI will allow for more actions on protected functions.
