### ISSUE TITLE
[BUG] Minimap icons aren't being faded

### ISSUE THREAD

**Issue by lshoravi** [PhenomDevel/BlizzHUDTweaks#67]
## Description
Having an in-combat fade to the minimap results in the icons themselves not being faded.

## Reproduce
1. Add In Combat Fade to minimap, I use 100%
2. Enter combat

## Expected Behaviour
Icons to fade out

## Optional Context (e.g. Screenshots)
![Screenshot 2024-04-26 at 18 47 49](https://github.com/PhenomDevel/BlizzHUDTweaks/assets/42211142/91585d21-3567-43e9-92f2-60b6ae2e12f5)

**Comment by PhenomDevel** [comment]
Hey, this is a know issue and nothing i'll be looking into. There are other addons like sexymap or similiar which can do this way better and it is not the easiest part. I tried and was'nt willing to invest the time into it, sry.
