### ISSUE TITLE
Bug Grabber spam

### ISSUE THREAD

**Issue by YamorinoGH** [PhenomDevel/BlizzHUDTweaks#68]
Hey there, I keep getting spammed with this:

1x [ADDON_ACTION_BLOCKED] AddOn 'WeakAuras' tried to call the protected function 'Frame:Hide()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `Hide'
[string "@WeakAuras/RegionTypes/DynamicGroup.lua"]:1589: in function `Resize'
[string "@WeakAuras/RegionTypes/DynamicGroup.lua"]:1528: in function `DoPositionChildren'
[string "@WeakAuras/Animations.lua"]:170: in function <WeakAuras/Animations.lua:162>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
}

**Comment by PhenomDevel** [comment]
My add-on is not mentioned a single time in the error message. 
The error you posted comes from WeakAuras:
`AddOn 'WeakAuras' tried to call the protected function 'Frame:Hide()'.`
