### ISSUE TITLE
[USABILITY] Clarifying the functionality of the main Toggles

### ISSUE THREAD

**Issue by Arkios64** [PhenomDevel/BlizzHUDTweaks#7]
![image](https://user-images.githubusercontent.com/78656397/203658399-69616829-653c-46bc-8f57-f4256845b383.png)
The Toggles alone would be easy enough to parse if you just played around with them once or used a bit of logic, but the description in the popup makes them confusing.
I would suggest either 
> Enable/Disable all class resource options

or
> Enable/Disable the sub module

Since the names of the modules are already directly above the Toggle, I would think the second one would be enough, tbh.

**Comment by PhenomDevel** [comment]
Yeah after reading them again i know exactly what you mean :D I'll change it later.

**Comment by PhenomDevel** [comment]
I changed the descriptions and should be fixed in `1.20.0-beta`
