### ISSUE TITLE
[BUG] Nothing working after todays patch

### ISSUE THREAD

**Issue by Persivle** [PhenomDevel/BlizzHUDTweaks#73]
## Description
The addon is enabled, but I can't access the menus for it, and nothing seems to be working? /blizzhudtweaks doesn't bring anything up, no minimap button, and no listing for it in the addon tab.

## Reproduce
> What steps are needed to reproduce it?
Seemingly nothing? I think todays update just broke it and I'm just letting you know.

## Expected Behaviour
It to work.

## Optional Context (e.g. Screenshots)
Thank you for your help and for making this addon. After noticing it not working today I realized just how much immersion this addon brings me. <3

**Comment by PhenomDevel** [comment]
1.47.4 fixes this issue. Will be available on the usual platforms in a few minutes.
