### ISSUE TITLE
[BUG] Experience/reputation bar mouseover area doesn't align with visual

### ISSUE THREAD

**Issue by 01d9a6aa** [PhenomDevel/BlizzHUDTweaks#75]
## Description
When placing the experience/reputation bar somewhere on the screen that's not bottom center, the mouse over interaction does not work in the area where the bar is placed, but when mousing over the bottom center of the screen the interaction works.

## Reproduce
1. Place experience/reputation bar somewhere not bottom center
2. Set to 0 alpha always unless mousing over
3. Mouse over the selected position of the bar from step 1 (bar does not show)
4. Mouse over bottom center of screen (bar shows in selected position)

## Expected Behaviour
Mousing over selected position shows bar, mousing over bottom of screen does nothing.

**Comment by PhenomDevel** [comment]
Should be fixed in the new version.
