### ISSUE TITLE
[FEATURE] Status Bar 2 Not Part of 'StatusTrackingBarManager' Frame

### ISSUE THREAD

**Issue by scotth523** [PhenomDevel/BlizzHUDTweaks#76]
Wasn't sure if this was a bug or feature. I leaning towards feature since it's only a bug you're under Lv80):

Blizzards's 'status bar 2' (rep bar when exp bar is active) isn't fading with any frame (tested with global settings) and should be fading out with exp/status bar 1, which is part of the 'StatusTrackingBarManager' frame. Granted, once you hit Lv80, status bar 2 becomes inactive.

Blizzard's 'status bar 2' should be part of StatusTrackingBarManager frame unless it's not possible.

**Comment by PhenomDevel** [comment]
Should be fixed in 1.48.8
