### ISSUE TITLE
[BUG] Toggle Keybind ignores modifiers

### ISSUE THREAD

**Issue by heipl-paul** [PhenomDevel/BlizzHUDTweaks#78]
## Description
As far as I can tell, blizzard UI knows how to take into consideration modifier keys, so I'm guessing your code does not. What I mean is that I toggle my Mouseover Frame Fading with `~`, and I have a dismount macro on `ctrl` + `shift` + `~` and dismounting also toggles Mouseover Frame Fading. Because I press `~`, it does not care that it is accompanied by `ctrl` / `alt` / `shift` or any combination of them. 

## Reproduce
1. Bind this addon to a button, let's say `X`
2. Bind something else with `X` and any modifier key. Let's say `shift`
3. Try to only activate the second binding with `shift` + `X`

## Expected Behaviour
Only the second binding is triggered

## Actual Behaviour
Both key bindings are triggered.

**Comment by PhenomDevel** [comment]
1.49.1 will be available soon and should fix this.

**Comment by PhenomDevel** [comment]
The Version did not correctly build. I will have lock later.

**Comment by PhenomDevel** [comment]
1.49.2 should now fix it.
