### ISSUE TITLE
[BUG] Mousing over the middle of the screen causes frames to show

### ISSUE THREAD

**Issue by Alfheimen** [PhenomDevel/BlizzHUDTweaks#80]
## Description
Frames will appear when mousing over the middle of the screen, as if there is some hidden UI element there.

## Reproduce
1. Enable settings to hide some UI elements.
2. Move cursor to middle of the screen.
3. Frames should appear.

## Expected Behaviour
Frames should remain hidden.

## Optional Context (e.g. Screenshots)
[GIF of behaviour](https://gyazo.com/34bbc7824db54b39382735f4843053d0)

**Comment by PhenomDevel** [comment]
This behavious occurs when there are disabled actionsbar in the middle of the screen. There is no fix yet. So i'd recommend enabling them and moving them out of the way before disabling them again.
