### ISSUE TITLE
[BUG] SpellFlyout not inheriting mouseover alpha from parent action bar

### ISSUE THREAD

**Issue by markoleptic** [PhenomDevel/BlizzHUDTweaks#81]
## Description
Spell flyouts such as mage teleport or mage portal do not inherit the mouseover alpha from their parent action bar. 

## Reproduce
Global Settings -> Out of Combat Fade, set to enabled with alpha of 0 and fade delay of 0.
Action Bar 1-8 using global settings.
Click mage portal flyout button on any action bar.
As soon as the mouse cursor is no longer hovering over the parent action bar (but still hovering over the flyout), the flyout is hidden.

## Expected Behavior
I expected any spell flyout that has mouseover to be treated as if I was mousing over the parent action bar. 

For example, if I am mousing over a spell flyout from ActionBar2 and ActionBar2 is linked to ActionBar1, I expected ActionBar1, ActionBar2, and the spell flyout to all be shown.

## Optional Context
I'm assuming the hooks for the SpellFlyout in OnEnter and OnLeave might be there to try to accomplish the expected behavior, but not be working as intended.

I have implemented a fix (for my use case at least). Would you like me to open a pull request for it?

**Comment by PhenomDevel** [comment]
Hey, I'd like you to submit a pull request when you have something working for you. That way, I don't have to do it myself, and I can check what you've done for sure!

**Comment by markoleptic** [comment]
Roger, I opened one

**Comment by PhenomDevel** [comment]
Fixed with https://github.com/PhenomDevel/BlizzHUDTweaks/pull/82
Available in 1.49.4
